apiVersion: v1
kind: Pod
spec:
  containers:
  - name: maven
    image: maven:3.8-openjdk-11
    command:
    - cat
    tty: true
    env:
    - name: DOCKER_HOST
      value: tcp://localhost:2376
    - name: DOCKER_TLS_VERIFY
      value: "1"
    - name: DOCKER_CERT_PATH
      value: /certs/client
    volumeMounts:
    - name: maven-cache
      mountPath: /root/.m2
    - name: docker-certs
      mountPath: /certs/client
      readOnly: true
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
        ephemeral-storage: "5Gi"
      limits:
        memory: "4Gi"
        cpu: "2"
        ephemeral-storage: "10Gi"
        
  - name: docker
    image: docker:dind
    securityContext:
      privileged: true
    env:
    - name: DOCKER_TLS_CERTDIR
      value: /certs
    volumeMounts:
    - name: docker-certs
      mountPath: /certs/client
    - name: docker-storage
      mountPath: /var/lib/docker
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
        ephemeral-storage: "20Gi"
      limits:
        memory: "4Gi"
        cpu: "2"
        ephemeral-storage: "50Gi"
        
  volumes:
  - name: maven-cache
    emptyDir:
      sizeLimit: 5Gi
  - name: docker-certs
    emptyDir: {}
  - name: docker-storage
    emptyDir:
      sizeLimit: 10Gi
